[build]
  # Указываем базовую директорию - папку с package.json
  base = "project"
  # Команда сборки для Next.js
  command = "npm install && npm run build"
  # Папка для публикации Next.js (out для статического экспорта)
  publish = "project/out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://aa17-07-2025.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"