[build]
  command = "cd project && npm install && npm run build"
  publish = "project/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://aa17-07-2025.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"