[build]
  # Указываем базовую директорию - папку с package.json
  base = "project"
  # Команда сборки
  command = "npm run build"
  # Папка для публикации (зависит от вашего фреймворка)
  publish = "project/.next"  # или project/.next если Next.js, или project/build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://aa17-07-2025.netlify.app"