[build]
  command = "cd project && npm install && npm run build"
  publish = "project/out" # Изменено с .next на out

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://aa17-07-2025.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"
